# Generated by Django 4.2.8 on 2024-01-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('LogId', models.AutoField(primary_key=True, serialize=False)),
                ('Message', models.CharField(default='', max_length=200, null=True)),
                ('LogLevel', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('Timestamp', models.DateTimeField(auto_now=True)),
                ('UserEmail', models.CharField(max_length=100)),
                ('Operation', models.CharField(default=None, max_length=50, null=True)),
                ('Success', models.IntegerField(default=None, max_length=1, null=True)),
            ],
        ),
    ]
