# Generated by Django 4.2.8 on 2024-01-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='UserEmail',
        ),
        migrations.AddField(
            model_name='log',
            name='UserId',
            field=models.IntegerField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
