# Generated by Django 4.2.8 on 2024-01-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logging', '0002_remove_log_useremail_log_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='UserId',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
