# Generated by Django 4.2.8 on 2024-01-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logging', '0003_alter_log_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='SessionId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
