# Generated by Django 4.2.8 on 2023-12-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyNetworkApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistAssocs',
            fields=[
                ('AssocId', models.AutoField(primary_key=True, serialize=False)),
                ('SourceId', models.CharField(max_length=100)),
                ('TargetId', models.CharField(max_length=100)),
                ('Weight', models.IntegerField()),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
    ]
