# Generated by Django 4.2.8 on 2023-12-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistAssocs',
            fields=[
                ('AssocId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.CharField(max_length=100)),
                ('SourceId', models.CharField(max_length=100)),
                ('TargetId', models.CharField(max_length=100)),
                ('Weight', models.IntegerField()),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('ArtistId', models.AutoField(primary_key=True, serialize=False)),
                ('ArtistName', models.CharField(max_length=100)),
                ('ArtistPopularity', models.IntegerField()),
                ('ArtistGenre', models.JSONField()),
                ('ArtistRank', models.IntegerField()),
                ('ArtistImage', models.CharField(max_length=100)),
                ('SimilarArtists', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserEmail', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
            ],
        ),
    ]
