# Generated by Django 4.2.8 on 2023-12-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyNetworkApp', '0002_alter_artists_artistid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistassocs',
            name='AssocId',
        ),
        migrations.RemoveField(
            model_name='artistassocs',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='artistassocs',
            name='UserId',
        ),
        migrations.AddField(
            model_name='artistassocs',
            name='SharedGenres',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistassocs',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='artistassocs',
            constraint=models.UniqueConstraint(fields=('SourceId', 'TargetId'), name='composite_primary_key'),
        ),
    ]
