# Generated by Django 4.2.8 on 2023-12-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyNetworkApp', '0003_artistassocs_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='UserEmail',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
