# Generated by Django 4.2.8 on 2023-12-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyNetworkApp', '0003_remove_artistassocs_associd_remove_artistassocs_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistassocs',
            name='id',
        ),
        migrations.AddField(
            model_name='artistassocs',
            name='AssocId',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
