# Generated by Django 4.2.8 on 2023-12-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyNetworkApp', '0004_remove_artistassocs_id_artistassocs_associd'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistassocs',
            name='SourceName',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistassocs',
            name='TargetName',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
