# Generated by Django 4.2.8 on 2023-12-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyNetworkApp', '0005_artistassocs_sourcename_artistassocs_targetname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistNetworks',
            fields=[
                ('NetworkId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField()),
                ('SessionId', models.CharField(max_length=50)),
                ('Nodes', models.JSONField()),
                ('Links', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='artists',
            name='ArtistRank',
        ),
    ]
