# Generated by Django 4.2.8 on 2023-12-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyNetworkApp', '0006_artistnetworks_remove_artists_artistrank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistnetworks',
            name='UserId',
        ),
        migrations.AddField(
            model_name='artistnetworks',
            name='Timeframe',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
