# Generated by Django 4.2.9 on 2024-03-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyNetworkApp', '0007_remove_artistnetworks_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='ArtistUrl',
            field=models.CharField(default='https:/spotify.com', max_length=100),
            preserve_default=False,
        ),
    ]
